### PR TITLE
Remove calls to deprecated imp module

### LINKED ISSUE #1053: DeprecationWarning for imp module in tax_benefit_system.py
>  /home/mghenis/anaconda3/lib/python3.8/site-packages/openfisca_core/taxbenefitsystems/tax_benefit_system.py:10: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
    from imp import find_module, load_module

https://github.com/openfisca/openfisca-core/blob/195fa723f1418e215a0c9eb351a96bd181cba10a/openfisca_core/taxbenefitsystems/tax_benefit_system.py#L10

### PR DESCRIPTION
**Pull request by benjello**
#### Technical changes

- Replace calls to deprecated `imp` module with `importlib` and `sys`. Fixes #1053.

I successfully ran `make test` locally.

Reopening #1087 cause of merge commit

### CODE REVIEW

**Comment by MaxGhenis** [comment]
Looks like this just needs a version bump?

**Review by MaxGhenis — APPROVED** [review]

**Comment by MaxGhenis** [comment]
@MattiSG @maukoquiroga @sandcha could you please review?

**Comment by benjello** [comment]
Or @eraviart ?

**Review by eraviart — APPROVED** [review]
It seems to be a canonical way to replace find_module & load_module using importlib (cf https://bugs.python.org/issue43540)

**Pull request merged**
