### PR TITLE
Refactor entities handling and formula syntax

### PR DESCRIPTION
**Pull request by fpagnoux**
## Goal

The main goal of this PR was to refactor entities handling, as discussed in https://github.com/openfisca/openfisca-core/issues/408. I went a little further, and came out with a proposition to write formulas in a simpler and more natural way. Any opinion will be appreciated.

@edarin @cbenz @laem, there are a few changes since our discussion, mainly the introduction implicit projection. It is documented below, but in a sentence, `individu.menage('loyer')` is now an array with value for Individus, not for Menages.

@benjello this is a big PR and I didn't have an occasion to talk to you about it in real life. Don't hesitate if you have questions, and hopefully we can talk about it in the next weeks.

France tests are passing. Todo:
- [x] Document formula writing and entity conversion/aggregation in the doc
- [x] Repair `measure_perfomances.py`
- [x] Adapt Web-API
- [x] Adapt Parsers

### CODE REVIEW

**Comment by fpagnoux** [comment]
## 1. New formula syntax

Let's start with an example:

Before:

``` py
class revenu_disponible(Variable):
    column = FloatCol
    entity_class = Individus
    label = u"Revenu disponible de l'individu"

    def function(self, simulation, period):
        period = period.start.period(u'year').offset('first-of')
        rsa = simulation.calculate_add('rsa', period)
        salaire_imposable = simulation.calculate('salaire_imposable', period)
        taux = simulation.legislation_at(period.start).impot.taux

        return period, rsa + salaire_imposable * (1 - taux)
```

After:

``` py
class revenu_disponible(Variable):
    column = FloatCol
    entity = Individu
    label = u"Revenu disponible de l'individu"

    def function(individu, period, legislation):
        period = period.start.period(u'year').offset('first-of')
        rsa = individu('rsa', period, options = [ADD])
        salaire_imposable = individu('salaire_imposable', period)
        taux = legislation(period).impot.taux

        return period, rsa + salaire_imposable * (1 - taux)
```
#### Changes
- The object simulation is not the main object the formula writer uses. Instead, everything is about the *object* of your calculation, for instance a person, or a family. As $laem first mentioned, calculating the `salary` of a person seems more natural, in the context of writing formulas, than calculating the `salary` of the simulation. The simulation object, who is more about the simulation execution than the formula definition, is not a concept the formula writer needs to care about.

- We use `individu` singular, as a formula is conceptually written for **a** person. The underlying object is of course vectorial, but this is an implementation problem that the formula writer should have to worry about the least as possible.

- The `legislation` is now the (optional) third argument of a formula. It is a function that can be called with a period (or an instant) for argument, and will compute the legislation at `period.start`.
-  We don't use `calculate_add` and equivalents. We discussed with $michelbl that `add` and `divide` would better be just an option of the calculation, and not a fully different method.
- We rename `entity_class` to `entity`: the formula writer just needs to mention what is the object of his.her formula, the concept of class is not needed. <sup><sub>This modification is currently reverted to reduce france changelog, but will be re-added.</sub><sup>

- We don't explicitly use a `calculate` method, but the `person('salary', period)` notation instead. It is less heavy than the current syntax, and it reduces the cognitive load when reading a formula.

**Comment by fpagnoux** [comment]
## 2. Handling entities

The new notation brings powerful feature to simplify entity casting.

### Conversions 

They are most often implicit, for instance:
```py
    # AF value casted for an individu
    af = individu.famille('af') 

    # Loyer casted to the famille entity, using the demandeur as a pivot
    loyer = famille.demandeur.menage('loyer')

    # Salaire casted to the FoyerFiscal entity, taking the value from a given role. 
    # Only works for a unique role.       
    salaire_declarant1 = foyer_fiscal.declarant_principal('salaire_net')
```

You can go pretty far with this notation, as you can see in [this test case](https://github.com/openfisca/openfisca-france/blob/refactor-entities/openfisca_france/tests/test_entities.py#L148).
         
### Aggregation
We still have two steps, but the syntax is really light.

```py
    salaire_net = famille.members('salaire_net')
    salaire_total_famille = famille.sum(salaire_net)
    salaire_max_dans_famille = famille.max(salaire_net)
    salaire_min_parents_famille = famille.min(salaire_net, role = Famille.PARENT)
    everyone_has_salary = famille.all(salaire_net > 0)
    anyone_has_salary = famille.any(salaire_net > 0)
```

Syntactic sugar like `famille.sum('salaire_net')` can be added later.

### Roles
New roles are not anymore exposed in the global scope, but attached to the corresponding entity, as you can see in the exemple above. To know if a person has a given role, use:
```py
    individu.has_role(Famille.PARENT)
```
Some roles can be included in each other:
```py
    individu.has_role(FoyerFiscal.DECLARANT)
     >>> [True, True, False, False]

    individu.has_role(FoyerFiscal.CONJOINT)
    >>> [False, True, False, False]
```
Note that unlike in the former system, there isn't a different role for the 1st child, 2nd child, etc. 


### Implementation

The constraint of staying in vectorial mode has been respected. Aggregations are based on the native `numpy.bincount`. We sometimes iterate on the roles, or on the positions in the entity, but never explicitly on the entities themselves.

This of course had a big cost and limit the possibilities. However, all has been made so that the vectorial aspect is hidden, or a least is not an obstacle to the formula writer.

**Comment by fpagnoux** [comment]
## 3. Breaking changes
- The two conversions columns, `EntityToPersonColumn` and `PersonToEntityColumn`, are deprecated.
- Variables such as `quifam` or `idfam` don't exist anymore. The entity management is now an internal business of each entity. 
- The way entities are declared has changes. You can see the new syntax [here](https://github.com/openfisca/openfisca-france/blob/refactor-entities/openfisca_france/entities.py). The goal was also to make it lighter and avoid repetitions.
- Renaming `entity_class`  -> `entity`

Other than this, the changes are **retro-compatible**, through [introspection of the formula signature](https://github.com/openfisca/openfisca-core/blob/refactor-entities/openfisca_core/formulas.py#L457). If the first argument of the formula is `self`, for instance in `def function('self', simulation, period)`, it will be interpreted as an "old-style" formula. This way, we can progressively and opportunistically rewrite formulas without having to all at once.

The former roles and entities formulas are not fully deprecated either. I wanted to do it, but there are many formulas in France that use them, and some of them are very hard to understand. Some treat differently children, based on their rank in the family, which seems wrong as this rank is arbitrary and not necessarily by age.

 Deprecating former roles and entity conversion methods  should probably be the first step of the `openfisca-france` migration.

**Comment by laem** [comment]
Awesome PR, and amazing explanation.

**Comment by benjello** [comment]
Nice work. Lots of interesting things. Need some time to process. Expect a return by the middle of next week if it is ok for you @fpagnoux

**Comment by edarin** [comment]
Actually I would like to see with you how to upgrade the docs to take into account your refactoring.

Especially here : https://doc.openfisca.fr/en/thinking-in-vectors.html#casting-from-an-entity-to-another

**Comment by fpagnoux** [comment]
Most of this page is probably to be thrown away ;). Let's write a new doc ;)

**Comment by edarin** [comment]
Just a question for an end user :

when you want to calculate variable for entities in your scenario, do you still have to launch a simulation ?

```
simulation = scenario.new_simulation()
```
I have the feeling that now this step isn't necessary.

**Comment by edarin** [comment]
Just a question for an end user :

when you want to calculate variable for entities in your scenario, do you still have to launch a simulation ?

```
simulation = scenario.new_simulation()
```
I have the feeling that now this step isn't necessary.

**Comment by edarin** [comment]
Just a question for an end user :

when you want to calculate variable for entities in your scenario, do you still have to launch a simulation ?

```
simulation = scenario.new_simulation()
```
I have the feeling that now this step isn't necessary.

**Comment by edarin** [comment]
Just a question for an end user :

when you want to calculate variable for entities in your scenario, do you still have to launch a simulation ?

```
simulation = scenario.new_simulation()
```
I have the feeling that now this step isn't necessary.

**Comment by edarin** [comment]
Just a question for an end user :

when you want to calculate variable for entities in your scenario, do you still have to launch a simulation ?

```
simulation = scenario.new_simulation()
```
I have the feeling that now this step isn't necessary.

**Comment by fpagnoux** [comment]
This hasn't changed, you still need, in the very beginning, to build a new simulation:

```py
simulation = scenario.new_simulation()
rsa = simulation.famille('rsa') # or simulation.calculate('rsa'), which returns the same thing.
```

I think #402, started by @michelbl,  have an impact on this, but not this one.

**Comment by edarin** [comment]
but I thought that calling simulation was avoidable now : 
```
     salaire_imposable = individu('salaire_imposable', period)
```

**Comment by fpagnoux** [comment]
It is avoidable inside a formula, but the object `individu` has to come from somewhere. In the formula, it is a parameter of the function:
```py
   def function(individu, period):
     salaire_imposable = individu('salaire_imposable', period)
```

Outside of the formua, if the only available object you have is the scenario, you'll have to go through the simulation.

**Comment by edarin** [comment]
Nice. Thanks

**Comment by benjello** [comment]
Rien à  dire sur le fond:
 - Les notations me paraissent suffisamment claires pour limiter les quiproquo et bien plus simples que les notations utilisées jusque là. 
 - La PR respecte la vectorisation (je ne suis pas allé vérifier, je fais confiance ;-)).
 - Il y a un point sur lequel je dois être rassuré. Cette PR modifie-t-elle le chargement des données d'enquête [comme ici](https://github.com/openfisca/openfisca-france-data/blob/bca396af44f750e1ef2987f6aba07a65e72bf6ff/openfisca_france_data/surveys.py#L60).

Il reste donc à coordonner les prochaines étapes.  J'ai bien noté que cette PR respecte l'existant mais:
 - on ne veut pas traîner plusieurs notations différentes dans openfisca-france
 - mais aussi des différences entre france les autres "pays" (openfisca-france-indirect-taxation mais aussi Sénégal et Tunisie qui vont être présents à l'OGP)  
 - sachant que certaines transitions après un changement ne sont pas encore finies (openfisca-france-indirect-taxation utilisées @thomasdouenne)

IMHO, ce qui doit être fait est donc dans l'ordre:
 - merge baremes-ipp et master 
 - appliquer cette PR sur france/tunisie/tunisie-pension et senegal en s'assurant que cela fonctionne avec france-data
 - appliquer cette PR sur france-indirect-taxation 
 - retirer l'usage de l'ancienne syntaxe 

Je pense aussi qu'il est temps que l'on rédige collaborativement deux documents:
 - les principes à respecter (vectorisation, etc)
 - une roadmap respectant au mieux les roadmap des différentes parties prenantes

Je suis conscient que je fais partie des principales personnes n'ayant pas permit l'émergence 
de ces deux documents car je n'avais pas beaucoup de temps. Il faut être également conscient que toute avancée structurelle crée de la dette sur les autres projets qui ne peuvent suivre faute de temps/compétences disponibles au bon moment. 

ps: @fpagnoux: où intervient l'ordre des enfants ? Ouvre un ticket stp. Faut que l'on règle cela.

Encore merci @fpagnoux pour ce beau travail. Essayons d'en faire un cas d'école pour mieux structurer tout le projet. J'attends vos avis et suggestions sur la marche à suivre et les prochaines étapes, nombre d'entre vous sont bien plus expérimentés que moi en terme de gestion collaborative de projets libres.

**Comment by fpagnoux** [comment]
> Il y a un point sur lequel je dois être rassuré. Cette PR modifie-t-elle le chargement des données d'enquête comme ici ?

Difficile de répondre, c'est un module d'openfisca que je ne connais pas du tout. En regardant le code, oui, il va y avoir des ajustements à faire, notamment les `idfam` et cie qui ont disparu. Ce qui veut dire qu'à un moment, les mainteneurs de `france-data` auront à adapter leur code s'ils veulent utiliser la dernière version du `core`. 

(Je remarque quand même que tout ce code semble proche de celui qui génère les scenarios. Une fois cette PR et celle de @michelbl mergée, la gestion des inputs sera sans doute la partie la plus endettée d'Openfisca et nécessitera un nettoyage.)

**Comment by fpagnoux** [comment]
>on ne veut pas traîner plusieurs notations différentes dans openfisca-france

Ce n'est en effet pas idéal, mais une migration complète de toutes les formules est une condition trop lourde au merge de cette PR. Elle risquerait de rester en plan plusieurs mois, ce qui induirait un coût important de maintien à jour et de gestion des conflits à venir (comme avec `barames-ipp`).

**Comment by fpagnoux** [comment]
Sur les prochaines étapes, je pense qu'il faut distinguer l'agenda "centralisé" lié à cette PR, des différentes adaptations des packages divers de l'univers `openfisca`.

En principe, le versionning propre nous permet de laisser chaque acteur libre du moment où il choisira d'investir du temps pour effecteur la migration de son package. Cette migration devra être facilitée par une documentation claire, et éventuellement par un soutien ponctuel des auteurs de changements importants sur `core`.

La roadmap "centralisée" serait donc pour moi la suivante:

- [x] S'assurer que la proposition actuelle passe au moins tous les tests de `france`, afin de prouver qu'elle peut gérer les situations variées du monde openfisca.
- [ ] Documenter clairement les changements principaux, et les nouvelles modalités d'usages.
- [ ] Merger la PR sur core pour éviter le stock et acter que c'est la direction prise, pour que tous les travaux futurs se basent sur cette version.
- [ ] Au bout d'un temps à définir, déprécier l'ancienne syntaxe. Ce temps peut être sujet à discussion, fixé à l'avance ou pas, cela dépend de la stratégie de dépréciation d'openfisca.

Dans l'idéal, on aurait 2 avant 3, mais nous n'avons pas encore d'outil de documentation technique, donc on risque de n'avoir qu'une documentation que partielle dans un premier temps.

**Comment by benjello** [comment]
> Difficile de répondre, c'est un module d'openfisca que je ne connais pas du tout. En regardant le code, oui, il va y avoir des ajustements à faire, notamment les `idfam` et cie qui ont disparu. Ce qui veut dire qu'à un moment, les mainteneurs de `france-data` auront à adapter leur code s'ils veulent utiliser la dernière version du `core`. 

 > (Je remarque quand même que tout ce code semble proche de celui qui génère les scenarios. Une fois cette PR et celle de @michelbl mergée, la gestion des inputs sera sans doute la partie la plus endettée d'Openfisca et nécessitera un nettoyage.)

Où dis-je regarder pour commencer à comprendre comment modifier mon code ?

**Comment by fpagnoux** [comment]
## Breaking changes for simulation initialisation:

### Entity id and roles
Each `entity` manages the arrays containing the entity id and role for each individual: (former `idfam`, `quifam`...), through 4 attributes:
```py
entity.members_entity_id # Which entity does each individual belongs to
entity.members_role # Which role has each individual in this entity (role is an object)
entity.members_legacy_role # Which role has each individual in this entity (role is a number)
entity.members_position # Which position has each individual in the entity. Mainly used for internal business.
  ```
See an example [here](https://github.com/openfisca/openfisca-core/blob/4.0.0a1/openfisca_core/tests/test_entities.py#L35)
Attributes `entity.index_for_person_variable_name` and `entity.role_for_person_variable_name` therefore don't exist anymore.

### Simulation entities
`simulation.entity_by_key_singular` has been renamed to `simulation.entities`.
`simulation.entity_by_key_plural` has been deprecated.

### Other changes
`entity.is_persons_entity` has been renamed to `entity.is_person`

**Comment by fpagnoux** [comment]
Mon post précédent devrait pouvoir t'aiguiller dans la migration. Si des problèmes demeurent (dans l'idéal sous forme de tests unitaires qui plantent) je peux aider.

**Comment by fpagnoux** [comment]
Some documentation about formula writing : 
https://github.com/openfisca/openfisca-gitbook/blob/syntax-4/en/coding-the-legislation/Writing%20a%20formula.md

**Pull request merged**
