### PR TITLE
Document Makefile

### PR DESCRIPTION
**Pull request by maukoquiroga**
#### Non-technical changes

- Document Makefile
  - Add a comment to explain what each task does
  - Print a human friendly message when running a task

```
$ make test

[⚙] Delete builds and compiled python files...
[⚙] Compile python files to check for syntax errors...
[⚙] Run linters to check for syntax and style errors...
[⚙] Run static type checkers for type errors...
Success: no issues found in 131 source files
[⚙] Run openfisca-core tests...
...
```

### CODE REVIEW

**Review by HAEKADI — COMMENTED** [review]
Thank you for the addition @maukoquiroga 👍 The file is much clearer now :)

I tested the commands locally and they're all functional!

**Review by HAEKADI — APPROVED** [review]

**Comment by HAEKADI** [comment]
@maukoquiroga Should we do the same for `OpenFisca-France` and `Country-Template`? 
It might also be a good opportunity to address these [issues](https://github.com/openfisca/openfisca-france/pull/1650#issuecomment-901219387) 🤔  
cc @MattiSG

**Comment by MattiSG** [comment]
Should we not deprecate the Makefile entirely and replace it with a task runner that's less obsolete? 😅

**Comment by maukoquiroga** [comment]
Hello @MattiSG, I'm personally agnostic as I like make a lot.

However, I've been looking for pure Python alternatives, for these reasons:

- It's Python, so easier to maintain and test
- It's Python, so we can avoid the bash, zch, Windows limitations

There are two alternatives that look promising to me, [invoke](https://www.pyinvoke.org/) and [nox](https://nox.thea.codes/en/stable/).

Please do not hesitate to open an issue if you think it would be worth the effort 😃

**Comment by MattiSG** [comment]
Thanks @maukoquiroga! “`nox` is a command-line tool that automates testing in multiple Python environments” while “Invoke is a Python task execution tool & library”, so it seems only Invoke would be appropriate, no? 🙂

**Comment by maukoquiroga** [comment]
Yes, I mixed two different use cases. Take a look at it, it looks pretty awesome as a make replacement to me at least.

**Comment by maukoquiroga** [comment]
> @maukoquiroga Should we do the same for `OpenFisca-France` and `Country-Template`?
> It might also be a good opportunity to address these [issues](https://github.com/openfisca/openfisca-france/pull/1650#issuecomment-901219387) 🤔
> cc @MattiSG

Sorry @HAEKADI I completed missed this comment. Taking a look at the link now :)

**Comment by maukoquiroga** [comment]
I think `make` is not the best tool for dependency management. I'm not fully convinced by `poetry` but in #1015 I try to simplify things already just with `setuptools`, I'd appreciate your feedback :)

**Pull request merged**
