### PR TITLE
Correct style ignore: W503 rather than W504

### PR DESCRIPTION
**Pull request by maukoquiroga**
Ignore W503 to enforce Knuth's style.

### CODE REVIEW

**Comment by fpagnoux** [comment]
Any example of what this style enforces?

**Comment by sandcha** [comment]
@fpagnoux [This post](https://github.com/OCA/maintainer-quality-tools/issues/545#issue-316882979) gives an example.

**Comment by Morendil** [comment]
I've just merged a corresponding change in setup.cfg of openfisca-france, but including both W504 & W503 - should it be W503 only ?

**Comment by maukoquiroga** [comment]
@fpagnoux @Morendil It should be W504 only. 

It is not yet implemented in `pycodestyle`, but due to the next release.

It would enforce the style once we upgrade version.

**Comment by maukoquiroga** [comment]
> Any example of what this style enforces?

#735

**Pull request merged**
