### PR TITLE
Simulation delete arrays

### LINKED ISSUE #740: Improve input deleting arrays in Python
What I have to do:

````
simulation = ...
holder = simulation.persons.get_holder('salary')
holder.delete_arrays('2018-08')
````

What I'd prefer:

````
simulation = ...
simulation.delete_arrays('salary', '2018-08')
````
What do you folks think?

### PR DESCRIPTION
**Pull request by benjello**
Fix #740 

@maukoquiroga @fpagnoux : i also tried to make the doctest work for simulation

### CODE REVIEW

**Comment by benjello** [comment]
@maukoquiroga @fpagnoux @Morendil : I can merge this PR but do you know if doctests are executed in tests. It seems that it is not the case because the test passed but the doctest was failing locally.

**Comment by Morendil** [comment]
It's [supported](https://docs.pytest.org/en/latest/doctest.html) and seems enabled via `setup.cfg`. What do you get when running `make test` locally ?

**Comment by benjello** [comment]
Ok maybe the tests where not ran at all. Not expecting results

**Comment by Morendil** [comment]
OK, checked locally by introducing a deliberate error in doctests for `periods.py` and they are in fact not run in CI, thanks for catching that!

**Comment by benjello** [comment]
@Morendil : so should I rebase, bump and merge this Pr or should I wait for a fix ?

**Comment by Morendil** [comment]
The right command to run doctests would be `pytest --doctest-modules openfisca_core`, except that fails locally with a bunch of problems:
- `openfisca_core/scripts/find_placeholders.py` needs `bs4`
- `openfisca_core/scripts/measure_performances.py` fails with `Missing attribute 'definition_period' in definition of variable 'age_en_mois'` 
- `openfisca_core/scripts/measure_performances_fancy_indexing.py` depends on `openfisca_france` (!)
- `openfisca_core/scripts/remove_fuzzy.py` has an assertion failure
- `openfisca_core/scripts/migrations/v16_2_to_v17/xml_to_yaml.py` fails due to lacking `lxml`
- `openfisca_core/scripts/migrations/v16_2_to_v17/xml_to_yaml_country_template.py` and `openfisca_core/scripts/migrations/v16_2_to_v17/xml_to_yaml_extension_template.py` ditto
- `openfisca_core/conv.py` because PyTest mistakes `test_in_pop` for a test function
- …and probably more (I gave up here)

**Pull request merged**
