### PR TITLE
Fix YAML indentation in CHANGELOG.md

### PR DESCRIPTION
**Pull request by guillett**

### CODE REVIEW

**Comment by maukoquiroga** [comment]
Thanks @guillett.

I see we're required to bump version, should we

- Bump?
- Merge ignoring the check?

cc @openfisca/france-contrib-dinsic

**Comment by guillett** [comment]
To me, there is no to bump version. My 2 cts.

**Comment by Morendil** [comment]
I'll rebase & merge.

**Comment by guillett** [comment]
Merci beaucoup @Morendil.

**Pull request merged**
