### PR TITLE
Make sure ParameterNode:repr generates a valid YAML representation

### PR DESCRIPTION
**Pull request by guillett**
#### Technical changes

- Make sure `ParameterNode:repr` generates a valid YAML representation

### CODE REVIEW

**Comment by fpagnoux** [comment]
Thanks for your contribution @guillett !

**Comment by maukoquiroga** [comment]
Hi guys ! Thanks for the contribution. Could you help me understand / add:

- an exemple or explanation of what does it exactly change,
- is it an improvement or a bug correction?, and
- wouldn't a comprehension like that affect performance negatively?

I haven't tested myself thoroughly, but a ballpark running 10 times some tests gave me ~8% performance penalty (core). I hope I'm wrong! 😃

**Comment by fpagnoux** [comment]
> I haven't tested myself thoroughly, but a ballpark running 10 times some tests gave me ~8% performance penalty (core). I hope I'm wrong! 😃

The only method modified here is `__repr__ `, which is the magic method that tells how to display an object on a python console. I doubt this method is called when normally running tests, so a performance impact seems unlikely.

About the impact of this change, let's consider the following snippet of code:

```py
from openfisca_country_template import CountryTaxBenefitSystem
tbs = CountryTaxBenefitSystem()
tbs.parameters
```

**Before** @guillett's change, the following would have been printed in the console:

```
benefits:
  basic_income:
    2015-12-01: 600.0
  housing_allowance:
    2016-12-01: None
    2010-01-01: 0.25
taxes:
  social_security_contribution:
    - threshold:
        2013-01-01: 0.0
      rate:
        2017-01-01: 0.02
        2015-01-01: 0.04
        2013-01-01: 0.03
    - threshold:
        2017-01-01: 6000.0
        2016-01-01: 12300.0
        2015-01-01: 12200.0
        2014-01-01: 12100.0
        2013-01-01: 12000.0
      rate:
        2017-01-01: 0.06
        2015-01-01: 0.12
        2013-01-01: 0.1
    - threshold:
        2017-01-01: 12400.0
      rate:
        2017-01-01: 0.12
  income_tax_rate:
    2015-01-01: 0.15
    2014-01-01: 0.14
    2013-01-01: 0.13
    2012-01-01: 0.16
general:
  age_of_majority:
    1971-01-01: 18.0
    1945-01-01: 21.0
  age_of_retirement:
    2017-01-01: 62.0
    1951-07-01: 60.33
```

**After**, we know get this:

```
benefits:
  basic_income:
    2015-12-01: 600.0
  housing_allowance:
    2016-12-01: null
    2010-01-01: 0.25
taxes:
  social_security_contribution:
    brackets:
      - threshold:
          2013-01-01: 0.0
        rate:
          2017-01-01: 0.02
          2015-01-01: 0.04
          2013-01-01: 0.03
      - threshold:
          2017-01-01: 6000.0
          2016-01-01: 12300.0
          2015-01-01: 12200.0
          2014-01-01: 12100.0
          2013-01-01: 12000.0
        rate:
          2017-01-01: 0.06
          2015-01-01: 0.12
          2013-01-01: 0.1
      - threshold:
          2017-01-01: 12400.0
        rate:
          2017-01-01: 0.12
  income_tax_rate:
    2015-01-01: 0.15
    2014-01-01: 0.14
    2013-01-01: 0.13
    2012-01-01: 0.16
general:
  age_of_majority:
    1971-01-01: 18.0
    1945-01-01: 21.0
  age_of_retirement:
    2017-01-01: 62.0
    1951-07-01: 60.33
```

The difference is thin, but the key thing is that the second output is valid YAML (for instance it contains `null` instead of `None`), and also a valid OpenFisca parameters description.

I assume the reason @guillett did this change was that some users must have been surprised that the output printed in the console was somehow looking very much like YAML but not valid YAML.

**Comment by maukoquiroga** [comment]
Merci @fpagnoux

**Pull request merged**
