### PR TITLE
Add trim option to marginal rate computation

### PR DESCRIPTION
**Pull request by benjello**

### CODE REVIEW

**Comment by benjello** [comment]
@adrienpacifico: you can use this to trim the large marginal rate you may hit because of nonlinearities like seuil de non versement and kinks.
@cbenz you can merge this with no impact for other openfisca users

**Comment by adrienpacifico** [comment]
@benjello 
Thanx a lot. I did not try your trim function. 
To deal with that I'm currently using a smoothing function that gives the average value between n-1 and n+1 element of the array if the variation is too large.

What should be the typical value of your trim parameter ?

**Comment by benjello** [comment]
trim is a list of two elements. The marginal rates that are higher than the max of these two parameters or less than the min are converted to nan and thus not appear in the plots.

**Comment by adrienpacifico** [comment]
Thanx for you answer.
It solves big arterfacts that are higher than a given value (due to threshold, kinks, etc). But it doesn't solve  my fat lines issues :-) (as reported in [#349](https://github.com/openfisca/openfisca-core/issues/349)).

I need to find a good way to deal with that, other than reducing the number of observations :-).
(désolé je me sers un peu de cet espace comme si c'était un canard en plastique).

P.s : you might want to put a docstring for the function such that ones know that trim is supposed to be a two element array/list/tupple/whatever else.

**Comment by benjello** [comment]
Your problem is due to rounding. Reduce the number of points.

Le sam. 10 oct. 2015 16:44, adrienpacifico <notifications@github.com> a
écrit :

**Comment by adrienpacifico** [comment]
Yes I know I've been trying to do something a bit more fancy today, it's
not working perfectly but it's still something to improve.
Le 10 oct. 2015 18:21, "Mahdi Ben Jelloul" <notifications@github.com> a
écrit :

**Comment by benjello** [comment]
@cbenz, you can merge this without trouble

**Pull request merged**
