### PR TITLE
Remove unused simulation generator

### PR DESCRIPTION
**Pull request by Morendil**
Removes a script for generating random populations and initializing random variable arrays. This was not used in any published code, had become incompatible with current options for creating simulations, and was untested.

Fixes openfisca/openfisca-doc#113

### CODE REVIEW

**Comment by benjello** [comment]
@fpagnoux : I think we moved all what we needed to initialize large simulations to openfisca-survey-manager. And I do not see any dependance on the code potentially removed. Could you confirm that ?
Thanks !

**Comment by fpagnoux** [comment]
This piece of code was not directly related to the _real_ initialization of large simulations. 

It was mainly used for performances tests, to simulate a large population use-case when no real data is available.

**Comment by fpagnoux** [comment]
We should also make sure to document the associated doc page: https://openfisca.org/doc/openfisca-python-api/simulation_generator.html

**Comment by Morendil** [comment]
😅

**Comment by Morendil** [comment]
Closing as non-urgent and less important than working on other doc-related items.

**Pull request closed without merging**
