### PR TITLE
Rename LICENSE.AGPL.txt to LICENSE

### LINKED ISSUE #823: Rename LICENSE.AGPL.txt to LICENSE
I love OpenFisca.

I suggest renaming the license file so that github can display useful information about it.

### PR DESCRIPTION
**Pull request by bzg**
This is my first contribution, I hope this is the expected process. Let me know otherwise.

Fixes #823 

Using `LICENSE.AGPL.txt` as the name of the license file prevents Github from recognizing it as a license file. It is useful to let github recognize the license file because it allows github to display information about the rights of the users and developers. See for example the image below:

github-agpl-license

### CODE REVIEW

**Comment by sandcha** [comment]
Welcome to openfisca-core @bzg and thanks for this contribution! 
Yes, this is the expected process. 
You only need to explicit what this PR fixes (or what new feature it brings).
> For example: is it to make the license name more discoverable now that GitHub interface automatically displays a logo for license names when the license file is `LICENSE`?

**Comment by Morendil** [comment]
@sandcha This probably doesn't need a CHANGELOG entry, the license information isn't "functional code".

**Comment by bzg** [comment]
Thanks @sandcha for the directions! Point taken @Morendil.

@sandcha the commit message gives a (probably too-short) explanation. Do you mean that (1) the this explanation should be clearer and that (2) it should appear in the PR message on top of the commit message? If so, I'll update the PR message.

**Comment by bzg** [comment]
FTR: https://github.com/openfisca/openfisca-core/issues/823

**Comment by Morendil** [comment]
@bzg To avoid the extra process of editing CHANGELOG, would you please add one commit to your PR: navigate to .circleci/has-functional-changes.sh and change the IGNORE_DIFF_ON value to include the pattern LICENSE*

**Comment by bzg** [comment]
Done. Let me know if I need to bump the version in `setup.py` or if things are okay like this. Thanks!

**Comment by sandcha** [comment]
(1) It's better when the commit message describes the "why"/use case. 
It's mainly important for the title of the PR as it might be the title of the merge commit of this PR.
(2) Yes, please 🙂

**Comment by bzg** [comment]
@sandcha I added some explanations about the "why" in the PR message. Thanks!

**Comment by sandcha** [comment]
As there is an update of `setup.py` (for license), yes, we need to bump version in same [setup.py](https://github.com/openfisca/openfisca-core/blob/master/setup.py#L42) file and the [CHANGELOG](https://github.com/openfisca/openfisca-core/blob/master/CHANGELOG.md) (for version and short description) 🙃

**Comment by Morendil** [comment]
> As there is an update of `setup.py` (for license), yes, we need to bump version in same [setup.py](https://github.com/openfisca/openfisca-core/blob/master/setup.py#L42) file and the [CHANGELOG](https://github.com/openfisca/openfisca-core/blob/master/CHANGELOG.md) (for version and short description) 🙃

This is vexing.

**Comment by bzg** [comment]
I updated the `CHANGELOD.md` and `setup.py` files accordingly.

**Comment by sandcha** [comment]
@Morendil Yes, we might need to improve the script on setup.py diffs!

**Pull request merged**
