### PR TITLE
Require numpy < 1.13

### PR DESCRIPTION
**Pull request by michelbl**
numpy 1.13 breaks openfisca

### CODE REVIEW

**Comment by benjello** [comment]
@michelbl @fpagnoux : do you recall what was the problem with numpy 1.13 ?
Thanks !

**Comment by michelbl** [comment]
See https://docs.scipy.org/doc/numpy-1.13.0/release.html

I think it was about `negative()` or `substract()` : 
```
negative(bool_), TypeError when negative applied to booleans.
subtract(bool_, bool_), TypeError when subtracting boolean from boolean.
```

**Comment by benjello** [comment]
@michelbl : Do you have tracked down where the problems appeared in openfisca ?

**Comment by michelbl** [comment]
Can't recall exactly. It may have been hidden in the infix form `boolean_vector_a - boolean_vector_b`. Why are you interested in that issue ?

**Comment by benjello** [comment]
Thanks @michelbl : I am interested in keep openfisca code in line with latest version of main packages because people usually install openfisca on the top of distribution like anaconda or debian that usually provide latest version of those packages. And I want to avoid the pain of dealing with this kind of dependencies. In that line we should think on moving to python 3 too.

**Pull request merged**
