### PR TITLE
Implement printing trace tree from Python

### PR DESCRIPTION
**Pull request by cbenz**
Especially from notebooks:

```python
scenario = tax_benefit_system.new_scenario().init_single_entity(
    parent1=dict(salaire_de_base=25000),
    period=2014,
    )
simulation = scenario.new_simulation(trace=True)
simulation.calculate('irpp', 2014, print_trace=True)
```

Outputs:

```
irpp@foyers_fiscaux<2014>[-1193.05]
|---> iai@foyers_fiscaux<2014>[1193.05]
|     |---> iaidrdi@foyers_fiscaux<2014>[1193.05]
|     |     |---> ip_net@foyers_fiscaux<2014>[1193.05]
|     |     |---> reductions@foyers_fiscaux<2014>[0.0]
|     |---> plus_values@foyers_fiscaux<2014>[0.0]
|     |     |---> f3vg@foyers_fiscaux<2014>[0]
|     |     |---> f3vh@foyers_fiscaux<2014>[0]
|     |     |---> f3vl@foyers_fiscaux<2014>[0]
|     |     |---> f3vm@foyers_fiscaux<2014>[0]
|     |     |---> f3vi@individus<2014>[0]
|     |     |---> f3vf@individus<2014>[0]
|     |     |---> f3vd@individus<2014>[0]
|     |     |---> f3sa@foyers_fiscaux<2014>[0]
|     |     |---> rpns_pvce@individus<2014>[0.0]
|     |---> cont_rev_loc@foyers_fiscaux<2014>[0.0]
|     |     |---> f4bl@foyers_fiscaux<2014>[0]
|     |---> teicaa@foyers_fiscaux<2014>[0.0]
|     |     |---> f5qm@individus<2014>[0]
|---> credits_impot@foyers_fiscaux<2014>[0.0]
|     |---> accult@foyers_fiscaux<2014>[0.0]
|     |     |---> f7uo@foyers_fiscaux<2014>[0]
|     |---> aidper@foyers_fiscaux<2014>[0.0]
|     |     |---> maries_ou_pacses@foyers_fiscaux<2014>[False]
|     |     |---> nb_pac2@foyers_fiscaux<2014>[0.0]
|     |     |---> f7wj@foyers_fiscaux<2014>[0]
|     |     |---> f7wl@foyers_fiscaux<2014>[0]
|     |     |---> f7wr@foyers_fiscaux<2014>[0]
|     |---> assloy@foyers_fiscaux<2014>[0.0]
|     |     |---> f4bf@foyers_fiscaux<2014>[0]
|     |---> autent@foyers_fiscaux<2014>[0.0]
|     |     |---> f8uy@foyers_fiscaux<2014>[0]
|     |---> ci_garext@foyers_fiscaux<2014>[0.0]
|     |     |---> f7ga@foyers_fiscaux<2014>[0]
|     |     |---> f7gb@foyers_fiscaux<2014>[0]
|     |     |---> f7gc@foyers_fiscaux<2014>[0]
|     |     |---> f7ge@foyers_fiscaux<2014>[0]
|     |     |---> f7gf@foyers_fiscaux<2014>[0]
|     |     |---> f7gg@foyers_fiscaux<2014>[0]
|     |---> cotsyn@foyers_fiscaux<2014>[0.0]
|     |     |---> f7ac@individus<2014>[0]
|     |     |---> salaire_imposable@individus<2014>[20234.8]
|     |     |---> chomage_imposable@individus<2014>[0.0]
|     |     |---> retraite_imposable@individus<2014>[0.0]
|     |---> creimp@foyers_fiscaux<2014>[0.0]
|     |---> direpa@foyers_fiscaux<2014>[0.0]
|     |     |---> f2bg@foyers_fiscaux<2014>[0]
|     |---> drbail@foyers_fiscaux<2014>[0.0]
|     |     |---> f4tq@foyers_fiscaux<2014>[0]
|     |---> inthab@foyers_fiscaux<2014>[0.0]
|     |---> mecena@foyers_fiscaux<2014>[0.0]
|     |     |---> f7us@foyers_fiscaux<2014>[0]
|     |---> preetu@foyers_fiscaux<2014>[0.0]
|     |     |---> f7uk@foyers_fiscaux<2014>[0]
|     |     |---> f7vo@foyers_fiscaux<2014>[0]
|     |     |---> f7td@foyers_fiscaux<2014>[0]
|     |---> prlire@foyers_fiscaux<2014>[0.0]
|     |---> quaenv@foyers_fiscaux<2014>[0.0]
|     |---> saldom2@foyers_fiscaux<2014>[0.0]
|---> cehr@foyers_fiscaux<2014>[0.0]
|     |---> rfr@foyers_fiscaux<2014>[18211.8]
|     |     |---> rni@foyers_fiscaux<2014>[18211.8]
|     |     |---> f3va@individus<2014>[0]
|     |     |---> f3vi@individus<2014>[0]
|     |     |---> rfr_cd@foyers_fiscaux<2014>[0.0]
|     |     |---> rfr_rvcm@foyers_fiscaux<2014>[0.0]
|     |     |---> rpns_exon@individus<2014>[0.0]
|     |     |---> rpns_pvce@individus<2014>[0.0]
|     |     |---> rev_cap_lib@foyers_fiscaux<2014>[0.0]
|     |     |---> f3vz@foyers_fiscaux<2014>[0]
|     |     |---> microentreprise@foyers_fiscaux<2014>[0.0]
|     |---> nb_adult@foyers_fiscaux<2014>[1.0]
|     |     |---> maries_ou_pacses@foyers_fiscaux<2014>[False]
|     |     |---> celibataire_ou_divorce@foyers_fiscaux<2014>[True]
|     |     |---> veuf@foyers_fiscaux<2014>[False]
```

Other options available:

```python
simulation.calculate('irpp', 2014, print_trace=True, max_depth=-1)
simulation.calculate('irpp', 2014, print_trace=True, max_depth=-1, show_default_values=False)
```

### CODE REVIEW

**Comment by cbenz** [comment]
@fpagnoux Would you have a quick look?

**Comment by fpagnoux** [comment]
From the user's perspective, It seems repetitive to have `trace=True` and `print_trace=True`. Is-it because you need to record everything before the user calls `simulation.calculate` ?

**Comment by fpagnoux** [comment]
With `show_default_values=False`, I would get rid of the zeros ?

**Comment by fpagnoux** [comment]
I'll try to test this tomorrow, otherwise seems good to me.

**Comment by cbenz** [comment]
> From the user's perspective, It seems repetitive to have trace=True and print_trace=True. Is it because you need to record everything before the user calls simulation.calculate ?

Exactly. Do you have a better idea?

> With show_default_values=False, I would get rid of the zeros ?

Yes. But this is tricky because it skips whole levels of hierarchy, so it's not always convinient to read.

--

I still detected a bug this morning, I'm fixing it before merging.

**Comment by pierrehvz** [comment]
Bonjour,
I was writing tests for isf in openfisca and I was using your tool but it is not working for me with theses two variables (  `isf_tot` and `isf_apres_plaf` ) and I don't understand why:

My code is: 
```
from openfisca_france import FranceTaxBenefitSystem
tax_benefit_system = FranceTaxBenefitSystem()


scenario = tax_benefit_system.new_scenario().init_single_entity(
    parent1=dict(salaire_de_base=150000,
                 age = 60,
                 ),
    period=2016,
    foyer_fiscal = dict(
        b1ab = 2000000,
        b1bc = 100000,
        b1be = 100000,
        b1cf = 100000,
        b2nc = 1000
        ),
    )
simulation = scenario.new_simulation(trace=True)
simulation.calculate('isf_apres_plaf', 2016, print_trace=True)
```

and the error message is:

```
assert step is not None 
AssertionError
```

Thank you for your help !!

**Comment by cbenz** [comment]
Hi @pierrehvz ,

quel rapport avec la pull-request en cours ? As-tu fait "répondre" au mauvais mail ? ^^

Si c'est ça peux-tu réouvrir une issue plutôt ?

**Comment by benjello** [comment]
@cbenz : my fault.
@pierrehvz va ouvrir une nouvelle issue.

**Pull request merged**
