### PR TITLE
Document Role

### PR DESCRIPTION
**Pull request by maukoquiroga**
#### Technical changes

- Document `Role`.

### CODE REVIEW

**Review by MattiSG — COMMENTED** [review]
Thanks @maukoquiroga!

I can't evaluate the relevance of the documentation itself. @benjello maybe?

**Comment by benjello** [comment]
@maukoquiroga could you run the openfisca-france test suite with this version of core so we stress test it in real conditions and avoid some problem down the roads.

**Comment by maukoquiroga** [comment]
@benjello :

> 2380 passed, 313 warnings in 873.19s (0:14:33)

**Comment by maukoquiroga** [comment]
> Thanks @maukoquiroga!
> 
> I can't evaluate the relevance of the documentation itself. @benjello maybe?

Thanks @MattiSG . The documentation contains unit tests, maybe you could have an input on that.

**Review by MattiSG — APPROVED** [review]
At this stage, I see mostly syntax improvements, and addition of documentation. I prefer to switch to a shipping mindset and unblock this PR by applying the idea that some documentation is better than no documentation, and will approve even though I cannot guarantee the accuracy of the documentation contents themselves.

Thank you for your work and patience @maukoquiroga.

**Comment by maukoquiroga** [comment]
Thanks @MattiSG :) With lots of syntax improvements and doc, my hope is it'll be easier to propose and review big changes in the future without breaking things unadvertently.

**Comment by benjello** [comment]
@maukoquiroga : do you think this PR may produce this [bug](https://github.com/openfisca/openfisca-survey-manager/actions/runs/6381132067/job/17317034553#step:6:222) ?

**Comment by maukoquiroga** [comment]
Hi @benjello, at first view, no (but I encountered a similar issue while working in this PR). While #1194 is a first fix, `Role` continues to be non-hashable because its immutability can't be assured. Thanks for the fix!

**Comment by benjello** [comment]
#1194 fixed the trouble with the `openfisca-survey-manager` bug

**Comment by maukoquiroga** [comment]
After checking, in fact yes, sorry: this PR makes Role unhashable by giving it an `__eq__`. If a `Role` is intended to actually be hashable, then indeed `__eq__` should be rermoved.

**Comment by maukoquiroga** [comment]
I'll propose a PR in 5m. I'll just add a test in the doc so we know `Role` is meant to be hashable. No need for the `__hash__` method, just removing `__eq__`.

**Pull request merged**
